# import acbotics_pipeline.blocks.processes.detectors.pr_detect_bf_peak_1d # resolve dependencies
import acbotics_pipeline.blocks.processes.detectors.pr_energy_detector
import acbotics_pipeline.blocks.processes.detectors.pr_frequency_detector
import acbotics_pipeline.blocks.processes.detectors.pr_relative_energy_detector
import acbotics_pipeline.blocks.processes.detectors.pr_windowed_detector
