[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "acbotics_pipeline"
version = "0.0.2"
dependencies = [
	"scipy",
	"numpy",
	"matplotlib",
	"pandas-stubs",
	"icontract",
	"pyprctl",
	"future",
	"pandas",
	"mlsocket",
	"netifaces",
	"Cython",
	"soundfile",
	"pyaudio",
	"arlpy",	
	"cryptocode"
	#"gps",
	# "geotiff",
	# "imagecodecs",
	# "PySide2",
	#"pyqtgraph",
	# "acbotics_interface",
]

#[tool.setuptools.packages]
#find = {}  # Scanning implicit namespaces is active by default

[project.scripts]
#run-acsense-dashboard = "acsense_display.acsense_dashboard:acsense_dashboard"
# run-acsense-logger = "acsense_display.scripts.acsense_logger:acsense_logger"
